name: Update Resources HTML

on:
  push:
    branches:
      - main  # Adjust this to your default branch if different
  workflow_dispatch:  # Allows manual triggering

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'  # Matches the version in your error log

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script to update resources
        run: python generate_doc_links.py

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add resources.html
          git diff --staged --quiet || git commit -m "Update resources.html"
          git push
        shell: bash